name: iOS starter workflow

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v-ios*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build-llvm-macos:
    runs-on: macos-latest
    steps:
      - name: brew install
        run: brew install ninja cmake

      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: build macos
        run: ./bootstrap_macos.sh

  build-llvm-ios:
    needs: build-llvm-macos # dependency
    runs-on: macos-latest
    steps:
      # - name: Check out the repository to the runner
      #   uses: actions/checkout@v4
      - name: Run bootstrap iOS
        run: ./bootstrap_ios.sh

      - name: upload a.xcframework.zip
        uses: actions/upload-artifact@v3
        with:
          name: a.xcframework.zip
          path: a.xcframework.zip

      - name: upload lld.xcframework.zip
        uses: actions/upload-artifact@v3
        with:
          name: lld.xcframework.zip
          path: lld.xcframework.zip

      - name: upload llc.xcframework.zip
        uses: actions/upload-artifact@v3
        with:
          name: llc.xcframework.zip
          path: llc.xcframework.zip

      - name: upload clang.xcframework.zip
        uses: actions/upload-artifact@v3
        with:
          name: clang.xcframework.zip
          path: clang.xcframework.zip

      - name: upload dis.xcframework.zip
        uses: actions/upload-artifact@v3
        with:
          name: dis.xcframework.zip
          path: dis.xcframework.zip

      - name: upload libLLVM.xcframework.zip
        uses: actions/upload-artifact@v3
        with:
          name: libLLVM.xcframework.zip
          path: libLLVM.xcframework.zip

      - name: upload link.xcframework.zip
        uses: actions/upload-artifact@v3
        with:
          name: link.xcframework.zip
          path: link.xcframework.zip

      - name: upload lli.xcframework.zip
        uses: actions/upload-artifact@v3
        with:
          name: lli.xcframework.zip
          path: lli.xcframework.zip

      - name: upload nm.xcframework.zip
        uses: actions/upload-artifact@v3
        with:
          name: nm.xcframework.zip
          path: nm.xcframework.zip

      - name: upload opt.xcframework.zip
        uses: actions/upload-artifact@v3
        with:
          name: opt.xcframework.zip
          path: opt.xcframework.zip

    # - name: upload checksum.txt
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: checksum.txt
    #     path: checksum.txt
